# Generated by Django 2.0.5 on 2018-07-05 07:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, verbose_name='书名')),
                ('book_author', models.CharField(blank=True, max_length=30, verbose_name='作者')),
                ('book_introduction', models.CharField(blank=True, max_length=300, verbose_name='书的简介')),
                ('book_publish', models.CharField(blank=True, max_length=30, verbose_name='出版社')),
                ('book_language', models.CharField(blank=True, default='中文', max_length=5, verbose_name='语种')),
                ('book_price', models.CharField(blank=True, max_length=10, verbose_name='价格')),
                ('book_publish_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='出版时间')),
                ('book_ISBN', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('book_status', models.IntegerField(default=0, verbose_name='状态')),
                ('book_lend_count', models.IntegerField(default=0, verbose_name='借出次数')),
            ],
        ),
        migrations.CreateModel(
            name='Booksys_Person',
            fields=[
                ('BookSys_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('BookSys_User', models.CharField(max_length=30, verbose_name='用户名')),
                ('BookSys_Password', models.CharField(max_length=30, verbose_name='密码')),
                ('BookSys_Name', models.CharField(max_length=30, verbose_name='图书管理员姓名')),
                ('BookSys_Phone', models.BigIntegerField(verbose_name='联系方式')),
            ],
        ),
        migrations.CreateModel(
            name='Lend_Stream',
            fields=[
                ('lend_stream_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_stream_reader_name', models.CharField(blank=True, max_length=30, verbose_name='读者姓名')),
                ('lend_stream_book_name', models.CharField(blank=True, max_length=30, verbose_name='书名')),
                ('lend_stream_type', models.IntegerField(default=0, verbose_name='操作类型')),
            ],
        ),
        migrations.CreateModel(
            name='Read_Person',
            fields=[
                ('Person_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_User', models.CharField(max_length=30, verbose_name='用户名')),
                ('Person_Password', models.CharField(max_length=30, verbose_name='密码')),
                ('Person_Name', models.CharField(max_length=30, verbose_name='读者姓名')),
                ('Person_CanBorrow', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='可借余量')),
                ('Person_Phone', models.BigIntegerField(verbose_name='联系方式')),
            ],
        ),
        migrations.CreateModel(
            name='System_Person',
            fields=[
                ('System_Id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('System_User', models.CharField(max_length=30, verbose_name='用户名')),
                ('System_Password', models.CharField(max_length=30, verbose_name='密码')),
                ('System_Name', models.CharField(max_length=30, verbose_name='系统管理员姓名')),
                ('System_Phone', models.BigIntegerField(verbose_name='联系方式')),
            ],
        ),
    ]
